* org-index

  A personal adaptive index for org.
  
  org-index is a package for org-mode within emacs.

  Read below for a description.

  The current version is 5.9.0.

  Visit http://2484.de/org-index.html for a Screencast.

** Table of Contents

   - [[#about-this-package][About this Package]]
   - [[#files][Files]]
   - [[#making-a-new-release][Making a new Release]]
   - [[#latest-change-log][Latest Change Log]]

** About this Package

*** Purpose

    Fast search for selected org-nodes and things outside.
    
    org-index creates and updates an index table with keywords; each line
    either points to a heading in org, references something outside or
    carries a snippet of text to yank.  When searching the index, the set
    of matching lines is updated with every keystroke; results are sorted
    by usage count and date, so that recently or frequently used entries
    appear first in the list of results.
    
    Please note, that org-index uses org-id to add an id-property to all
    nodes in the index.
    
    In the addition to the index table, org-index introduces these
    supplemental concepts:
    
    - 'References' are decorated numbers (e.g. 'R237' or '--455--'); they are
       well suited to be used outside of org, e.g. in folder names,
       ticket systems or on printed documents.
    - 'Working set' (short: ws) is a small set of nodes for your daily work;
       it can be managed easily and traversed very fast.  All related tasks
       are also available through the interactive function
       org-index-working-set, which see.
    
    On first invocation org-index will assist you in creating the index
    table.
    
    To start using your index, invoke the subcommand 'add' to create
    index entries and 'occur' to find them.

*** Setup

    - org-index can be installed with package.el
    - Invoke `org-index'; on first run it will assist in creating your
      index table.
    
    - Optionally invoke `M-x org-customize', group 'Org Index', to tune
      its settings.

*** Further Information

    - Watch the screencast at http://2484.de/org-index.html.
    - See the documentation of `org-index', which can also be read by
      invoking `org-index' and typing '?'.

** Files

*** Implementation

    - org-index.el :: The complete lisp source

*** Building

    - Rakefile :: Helpful Ruby-Tasks for building

*** Tests
    
    In subdir tests.

    - oidx.el :: ert-tests for org-index
    - test.bat :: Windows command file to start a specifically prepared emacs for the tests
    - test-init.el :: Customizations for the tests

*** Screencasts
    
    In subdir screencast.

    These files have been used to produce the screencast on http://2484.de/org-index.html:

    - screencast.bat :: Windows command file to start a specifically prepared emacs for the screencast
    - screencast.el :: The lisp code used to play the screencast
    - screencast-init.el :: Customizations for screencast
    - screencast.org :: Internal Notes about the screencast
		       	
*** Custom merge-driver for git

    In subdir merge-driver.

    - merge-org-index.rb :: Simple ruby script to aid during git merges of your index table;
      see the comments within the file for instructions	 

** Making a new Release

*** Testing and checking

    - ert
    - (byte-compile-file "org-index.el")
    - elint-current-buffer
    - checkdoc
    - package-lint ;; ignore messages about oidx-prefix

*** Preparing

    - Update Version number in org-index.el
    - Update Change Log in org-index.el
    - Check and Update Commentary in org-index.el
    - Run rake to copy those pieces of information into 
      README.org and ChangeLog.org

** Latest Change Log

   See ChangeLog.org for older notes.

*** 5.9

    - Renamed 'focus' to 'working-set', changed commands and help texts accordingly.
    - Added special buffer to manage the working-set
  
*** 5.8

    - Timeout in prompt for additional focus-command
    - Popup to show current node during after focus change
    - Various changes to become ready for melpa
    - Refactored org-index--do-occur (now named oidx--do-occur), creating various new functions
    - Restructured source code, grouping related functions together; groups are separated as
      usual by ^L
    - Introduced the secondary prefix 'oidx--' and renamed everything starting with 'org-index--'.
      Functions and variables starting with 'org-index-' are left untouched.
    - Renamed functions org-index-dispatch to org-index, org-index to oidx--do and variable
      org-index-dispatch-key to org-index-key
  

