* org-index

  A personal adaptive index for org.
  
  org-index is a package for org-mode within emacs.

  Read below for a description.

  The current version is 6.1.0.

  Visit http://2484.de/org-index.html for a Screencast.

** Table of Contents

   - [[#about-this-package][About this Package]]
   - [[#files][Files]]
   - [[#releasing-a-new-version][Releasing a new version]]
   - [[#latest-change-log][Latest Change Log]]

** About this Package

*** Purpose

    Fast search for selected org-nodes and things outside.
    
    org-index creates and updates an index table with keywords; each line
    either points to a heading in org, references a folder outside of org
    or carries an url or a snippet of text.  When searching the index, the
    set of matching lines is updated with every keystroke; results are
    sorted by usage count and date, so that frequently or recently used
    entries appear first in the list of results.
    
    Please note, that org-index uses org-id throughout and therefore adds
    an id-property to all nodes in the index.
    
    In the addition to the index table, org-index introduces the concept of
    references: These are decorated numbers (e.g. 'R237' or '--455--');
    they are well suited to be used outside of org, e.g. in folder names,
    ticket systems or on printed documents.
    
    On first invocation org-index will assist you in creating the index
    table.
    
    To start using your index, invoke the subcommand 'add' to create
    index entries and 'occur' to find them.

*** Setup

    - org-index can be installed with package.el
    - Invoke `org-index'; on first run it will assist in creating your
      index table.
    
    - Optionally invoke `M-x org-customize', group 'Org Index', to tune
      its settings.

*** Further Information

    - Watch the screencast at http://2484.de/org-index.html.
    - See the documentation of `org-index', which can also be read by
      invoking `org-index' and typing '?'.

** Files

*** Implementation

    - org-index.el :: The complete lisp source

*** Building

    - Rakefile :: Helpful Ruby-Tasks for building

*** Tests
    
    In subdir tests.

    - oidx.el :: ert-tests for org-index
    - test.bat :: Windows command file to start a specifically prepared emacs for the tests
    - test-init.el :: Customizations for the tests

*** Screencasts
    
    In subdir screencast.

    These files have been used to produce the screencast on http://2484.de/org-index.html:

    - screencast.bat :: Windows command file to start a specifically prepared emacs for the screencast
    - screencast.el :: The lisp code used to play the screencast
    - screencast-init.el :: Customizations for screencast
    - screencast.org :: Internal Notes about the screencast
		       	
*** Custom merge-driver for git

    In subdir merge-driver.

    - merge-org-index.rb :: Simple ruby script to aid during git merges of your index table;
      see the comments within the file for instructions	 

** Releasing a new version

*** Testing and checking

    - ert
    - (byte-compile-file "org-index.el")
    - elint-current-buffer
    - checkdoc
    - package-lint-current-buffer ;; ignore messages about oidx-prefix

*** Preparing

    - Update Version number in org-index.el
    - Update Change Log in org-index.el
    - Check and update Commentary in org-index.el
    - Run rake to copy those pieces of information into 
      README.org and ChangeLog.org
    - git add/commit as appropriate 
    - git tag -a -m x.y.z x.y.z ; git push ; git push --tags

** Latest Change Log

   See ChangeLog.org for older notes.

*** 6.1

    - Added new command 'l' in occur to visit links
    - Modified keys in occur-buffer
  
*** 6.0

    - Moved the working-set feature into its own package org-working-set
  
*** 5.12

    - Do-not-clock is shown in working-set menu
    - Switching from working set circle into menu
    - RET in working-set circle ends and clocks in immediately
    - Fixes
  
*** 5.11

    - Implemented do-not-clock commands and behaviour in working-set
    - Fixes
  
*** 5.10

    - Pressing shift prevents clocking into working set
    - Occur shows '(more lines omitted)' if appropriate
    - replaced (org-at-table-p) with (org-match-line org-table-line-regexp)
      throughout for preformance reasons
    - Offer direct clock-in from result-buffer of occur
    - Various fixes
  
*** 5.9

    - Renamed 'focus' to 'working-set', changed commands and help texts accordingly.
    - Added special buffer to manage the working-set
    - Function org-index-working-set may now be invoked directly
    - Simplified working-set circle
    - Introduced org-index-occur-columns to limit matches during occur to specified
      number of leading columns; this gives better matches
    - Removed days option from occur command
    - Fixed and Optimized overlay-handling in occur for better performance and
      overall stability
    - Limited the number of lines to display in occur for better performance,
      see 'org-index-occur-max-lines'
  

